name: 'Setup'
description: 'Sets up a Javascript environment'

runs:
  using: 'composite'
  steps:
  - uses: oven-sh/setup-bun@v1
  - uses: actions/cache@v3
    with:
      path: node_modules
      key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}
      restore-keys: |
        ${{ runner.os }}-node-
  - run: bun install