name: 'Setup'
description: 'Sets up a Javascript environment'

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0 # Fetch all branches for nx base comparison
      submodules: recursive
      token: ${{ secrets.ACCESS_TOKEN }}
  - uses: oven-sh/setup-bun
  - run: bun install