# Base image for all dev images in this monorepo
FROM node:18-bullseye

RUN apt install -y curl
RUN curl -fsSL https://bun.sh/install | bash

WORKDIR /app

# Entrypoint is defined in docker-compose.yml