version: '3.4'
services:
  peepo:
    secrets:
      - peepo-token
    environment:
      - 'PS2GG_STAGING=true'
  jaeger:
    secrets:
      - jaeger-token
    environment:
      - 'PS2GG_STAGING=true'
  github:
    secrets:
      - gh-discord-token
      - gh-webhook-token

secrets:
  peepo-token:
    external: true
  jaeger-token:
    external: true
  gh-discord-token:
    external: true
  gh-webhook-token:
    external: true
