version: '3.4'
services:
  peepo:
    secrets:
      - peepo-token
    environment:
      - 'PS2GG_STAGING=true'
  jaeger:
    secrets:
      - jaeger-token
    environment:
      - 'PS2GG_STAGING=true'

secrets:
  peepo-token:
    external: true
  jaeger-token:
    external: true
