version: '3.4'
services:
  peepo:
    secrets:
      - peepo-token
  friends:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.friends.rule=(Host(`friends.localhost`) && PathPrefix(`/v1/friends`))"
      - "traefik.http.services.friends.loadbalancer.server.port=3000"
  jaeger:
    secrets:
      - jaeger-token
  github:
    secrets:
      - gh-discord-token
      - gh-webhook-token

secrets:
  peepo-token:
    external: true
  jaeger-token:
    external: true
  gh-discord-token:
    external: true
  gh-webhook-token:
    external: true
