version: '3.4'
services:
  peepo:
    secrets:
      - peepo-token
  jaeger:
    deploy:
      replicas: 0
  github:
    secrets:
      - gh-discord-token
      - gh-webhook-token

secrets:
  peepo-token:
    external: true
  gh-discord-token:
    external: true
  gh-webhook-token:
    external: true
