version: '3.4'
services:
  peepo:
    secrets:
      - discord_token_peepo

secrets:
  discord_token_peepo:
    external: true
  notifications_db_pass:
    external: true
  users_db_pass:
    external: true
  population_db_pass:
    external: true
  rabbitmq_pass:
    external: true
