networks:
  ps2gg_external:
    external: true
  ps2gg_internal:
    external: true
secrets:
  discord_token_peepo:
    external: true
services:
  census:
    entrypoint: sh /app/docker/entrypoint.dev.sh census
    image: 127.0.0.1:5000/ps2gg:dev
    networks:
      ps2gg_internal: null
    volumes:
    - /opt/ps2gg/ps2.gg:/app:rw
  notifications:
    entrypoint: sh /app/docker/entrypoint.dev.sh notifications
    environment:
      EVENT_STREAM_DSN: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      POSTGRES_DSN: postgresql://postgres:postgres@notifications_db/development
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 1m
      test: curl -f localhost:3000/healthz
      timeout: 5s
    image: 127.0.0.1:5000/ps2gg:dev
    networks:
      ps2gg_external: null
      ps2gg_internal: null
    volumes:
    - /opt/ps2gg/ps2.gg:/app:rw
  notifications_db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:15.2-alpine
    networks:
      ps2gg_internal: null
    volumes:
    - notifications_db:/var/lib/postgresql/data:rw
  overlay:
    entrypoint: sh /app/docker/entrypoint.dev.sh overlay
    image: 127.0.0.1:5000/ps2gg:dev
    networks:
      ps2gg_internal: null
    volumes:
    - /opt/ps2gg/ps2.gg:/app:rw
  peepo:
    entrypoint: sh /app/docker/entrypoint.dev.sh peepo
    image: 127.0.0.1:5000/ps2gg:dev
    networks:
      ps2gg_internal: null
    secrets:
    - source: discord_token_peepo
    volumes:
    - /opt/ps2gg/ps2.gg:/app:rw
  population:
    entrypoint: sh /app/docker/entrypoint.dev.sh population
    environment:
      EVENT_STREAM_DSN: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      POSTGRES_DSN: postgresql://postgres:postgres@notifications_db/development
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 1m
      test: curl -f localhost:3000/healthz
      timeout: 5s
    image: 127.0.0.1:5000/ps2gg:dev
    networks:
      ps2gg_external: null
      ps2gg_internal: null
    volumes:
    - /opt/ps2gg/ps2.gg:/app:rw
  population_db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:15.2-alpine
    networks:
      ps2gg_internal: null
    volumes:
    - population_db:/var/lib/postgresql/data:rw
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
    image: rabbitmq:3.8-alpine
    networks:
      ps2gg_internal: null
    volumes:
    - rabbitmq:/var/lib/rabbitmq:rw
  redis:
    image: redis:4.0-alpine
    networks:
      ps2gg_internal: null
    volumes:
    - redis:/data:rw
  users:
    entrypoint: sh /app/docker/entrypoint.dev.sh users
    environment:
      EVENT_STREAM_DSN: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      POSTGRES_DSN: postgresql://postgres:postgres@notifications_db/development
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 1m
      test: curl -f localhost:3000/healthz
      timeout: 5s
    image: 127.0.0.1:5000/ps2gg:dev
    networks:
      ps2gg_external: null
      ps2gg_internal: null
    volumes:
    - /opt/ps2gg/ps2.gg:/app:rw
  users_db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:15.2-alpine
    networks:
      ps2gg_internal: null
    volumes:
    - users_db:/var/lib/postgresql/data:rw
version: '3.4'
volumes:
  notifications_db: {}
  population_db: {}
  rabbitmq: {}
  redis: {}
  users_db: {}

