version: '3.4'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "8080:8080"
    networks:
      - ps2gg-external
      - ps2gg-internal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  rabbitmq:
    image: rabbitmq:3.8-alpine
    hostname: rabbitmq
    networks:
      - ps2gg-internal
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:4.0-alpine
    networks:
      - ps2gg-internal
    volumes:
      - redis:/data

networks:
  ps2gg-internal:
    external: true
  ps2gg-external:
    external: true

volumes:
  rabbitmq:
  redis:
