version: '3.4'

services:
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq-pass
    secrets:
      - rabbitmq-pass

secrets:
  rabbitmq-pass:
    external: true
