version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.8-alpine
    networks:
      - ps2gg-internal
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis:4.0-alpine
    networks:
      - ps2gg-internal
    volumes:
      - redis:/data
  #
  # Other services are generated through generate.ts
  #

networks:
  ps2gg-internal:
    external: true
  ps2gg-external:
    external: true

volumes:
  rabbitmq:
  redis:
