name: Push

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches for nx base comparison
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: ./.github/actions/setup
      - run: |
          services=""
          for dir in ./services/*/; do
            service=$(basename "$dir")
            services="$services,$service"
          done
          services="${services:1}"
          bun nx run-many --target=build --prod --projects="$services" --parallel=10

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches for nx base comparison
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: ./.github/actions/setup
      - run: bun nx affected:lint --base=origin/master --parallel=6

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches for nx base comparison
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: ./.github/actions/setup
      - run: bun nx affected:test --base=origin/master --parallel=6
