name: Push

on: [push]

jobs:
  affected:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: bun nx affected:lint --base=origin/master --parallel=12

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: bun nx affected:test --base=origin/master --parallel=12
